In [1]:
%pylab inline


Populating the interactive namespace from numpy and matplotlib


# NumPy: Beginner's Guide - Third Edition


# Using the NumPy arrange function


In [6]:
a = arange(5)

In [5]:
a.dtype

dtype('int64')

## Create a two-by-two array:

In [9]:
m = array([arange(2), arange(2)])

In [10]:
m

array([[0, 1],
       [0, 1]])

In [112]:
m.transpose()

array([[0, 0],
       [1, 1]])

In [11]:
m.shape

(2, 2)

In [12]:
help(array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

## Create a three-by-three array:

- use the array function of **NumPy**
- use the arrange function of **NumPy** to create a sequence of 3 numbers


In [13]:
n = array([arange(3), arange(3)])


In [14]:
n

array([[0, 1, 2],
       [0, 1, 2]])

## Selecting elements in an *ndarray*

In [15]:
a = array([[1, 2], [3, 4]])

In [16]:
a

array([[1, 2],
       [3, 4]])

In [17]:
a[0, 0]

1

In [18]:
a[0, 1]

2

In [19]:
a[1, 0]

3

In [20]:
a[1, 1]

4

## Data type objects

In [21]:
a.dtype.itemsize

8

## Record Type Example

In [22]:
t = dtype([('name', str_, 40), ('numitems', int32), ('price', float32)])

In [24]:
t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

## One dimensional clicing and indexing

In [25]:
a = arange(9)

In [26]:
a[3:7]

array([3, 4, 5, 6])

### Select elements from index 0 to 7 with steps of 2

In [27]:
a[:7:2] 

array([0, 2, 4, 6])

### Reverse the array

In [28]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

# Slicing multidimensional arrays

In [29]:
b = arange(24).reshape(2, 3, 4)

In [30]:
b.shape

(2, 3, 4)

## Array Structure

Think of this structure as a 2 story house with 12 rooms per floor
further broken into 3 rows and 4 columns

In [31]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
b[0, 0, 0]

0

#### Here we don't care about the floor, we just want the values at the given column and row

In [33]:
b[:, 0, 0]

array([ 0, 12])

In [36]:
b[:, 0, 1]

array([ 1, 13])

In [44]:
b[:, 1, 0]

array([ 4, 16])

In [69]:
b[:,1,:]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

#### First floor in the (2, 3, 4) array

In [34]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Second floor in the same array


In [35]:
b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Other alternatives to the above 

In [38]:
b[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
b[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Get the second row of the first floor

In [40]:
b[0, 1]

array([4, 5, 6, 7])

#### Now get every second element of the first floor


In [41]:
b[0, 1, ::2]

array([4, 6])

#### Using elipse to slice
The below command will give us all the rooms on both floors that are in the second column of the row

In [42]:
b[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

##### This is the same as the above


In [51]:
b[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [43]:
b[..., 0]

array([[ 0,  4,  8],
       [12, 16, 20]])

### Select the first floor last column

In [70]:
b[0,:, -1]

array([ 3,  7, 11])

# Manipulation of arrays

In [71]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [72]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [73]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [75]:
b.shape = (6, 4)

In [76]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [78]:
b.resize(2, 12)

In [79]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

## Summary

1. *ravel()* -- This is function returns a one dimmensional array with the same data as the imput array and doesn't always return a copy

2. *flatten()* -- This is a method of **ndarray** which flattens arrays and always returns a copy
3. *reshape()* -- This function modifies the shape of an array
4. *resize()* -- This function changes the shape of an array and adds the input array if necessary

## Stacking arrays

In [80]:
a = arange(9).reshape(3, 3)

In [81]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
b = 2 * a

In [83]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

#### Horizontal Array stacking

In [85]:
hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [86]:
concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

#### Vertrical Array stacking

In [87]:
vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [88]:
concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

#### Depth stacking

In [89]:
dstack((a,b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

#### Column stacking

In [90]:
oned = arange(2)

In [91]:
oned

array([0, 1])

In [92]:
twice_oned = oned * 2

In [93]:
twice_oned

array([0, 2])

In [95]:
column_stack((oned, twice_oned))

array([[0, 0],
       [1, 2]])

In [96]:
column_stack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [97]:
column_stack((a, b)) == hstack((a, b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

#### Row Stacking

In [98]:
row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [99]:
row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [100]:
row_stack((a, b)) == vstock((a, b))

NameError: name 'vstock' is not defined

#### Splitting arrays

In [101]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
hsplit(a, 3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [103]:
split(a, 3, axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [104]:
vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [105]:
split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [106]:
c = arange(27).reshape(3, 3, 3)

In [107]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [108]:
dsplit(c, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [109]:
b.ndim

2

In [117]:
a[a > 4][:2]

array([5, 6])

In [114]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])